### ISSUE TITLE
atom feed does not work

### ISSUE THREAD

**Issue by pangard** [OpenDreamKit/OpenDreamKit.github.io#58]
There is a link at the bottom of the website: "Add our Atom Feed to your feed reader", but the link

http://opendreamkit.org/news/atom.xml

stopped working at some point. Last feed I got was "Full-time open-ended research software engineer position at the University of Warwick.", on december 2016.

Regards

**Comment by nthiery** [comment]
@VivianePons, @defeo: this probably is related to the web site refactoring. Ideas on how to resolve that?

Thanks!

**Comment by defeo** [comment]
The feed is here: http://opendreamkit.org/atom.xml. It might have been moved since Dec. 2016, I'm too lazy to check. But I can't see any broken link on the page.
Just update the link in your feed reader, and you should be fine.

**Comment by nthiery** [comment]
Thanks for the feedback. Since this will impact each of our followers, it would be nice to put a "redirect" of some sort from the old page to the new one.

**Comment by pangard** [comment]
ok, thanks.

Actually, I checked that I had the "good" feed in thunderbird:

http://opendreamkit.org/atom.xml

That link worked **on thunderbird** fine up to "Full-time open-ended research software engineer position at the University of Warwick.", on december 2016, but then it stopped working **on thunderbird** and it doesn't work now.

I though may be one particular item is malformed or whatever, so I have installed a different rss reader and it had no problem with your feed.

**Comment by defeo** [comment]
So I actually found the broken link, thanks `git grep`! It was a `../atom.xml` in place of `/atom.xml`, so it used to point to a whole bunch of different urls depending on the page it was on.

The `/news/atom.xml` URL has never worked, so a redirect as suggested by @nthiery is unnecessary.

Concerning your Thunderbird problem, that's weird. The feed used to be invalid XML since Dec 2015, because of an unescaped `&`. However, no other error was introduced since, so it is weird that Thunderbird stopped working on Dec 2016.

From time to time we introduce more serious bugs in `atom.xml`, that could possibly make Thunderbird unhappy. The last occurence I am aware of was on May 5, and was fixed on May 12. However there have been blog posts between Dec. 2016 and last May, so it'd be weird if that was the culprit.

Anyway, thanks for reporting.
